before_deploy: cd build/src
node_js: 
- "0.10"
env: 
  global: 
    secure: ZoAieh02PFSl12IgeO8pJKEKRBbl0qWFWdDwFJDCvEULKdkhFhSPaEe7b9LPqGFcWLU4Z+kzlpe/gsXfSQ51XaAMm1lONhAs+d9/GdaakQmdSFaSnbm37845cppX/3K2oT6AjmUenom9Gx6A/nasuftZfIWYwXUhdP4nXAMEf8o=
deploy: 
  provider: npm
  email: hendrik@helwich.de
  skip_cleanup: true
  api_key: 
    secure: ed4k7u/W6Sb6GVmRiMt7gfBry7VTXKefJ+LJLowQDallDVuzcVwqKcwFmG8S4fKJHxewkmghA7uX/Be/zB3MYj/HKIeSRregJghLoO3Yewfec56LZX64LL25jlqHw8xrC01jXIyLnxpKSBJ4m0mPqFue/u0iHErZP7At9MkHq/4=
language: node_js
